// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/cce31af92dc06fbd620d48ff55a9904be20ddc61/koa-logger/index.d.ts
declare module 'koa-logger' {
// Type definitions for koa-logger v2.0
// Project: https://github.com/koajs/logger
// Definitions by: Joshua DeVinney <https://github.com/geoffreak>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

/// <reference types="koa"/>

import * as Koa from 'koa';

function KoaLogger(): Koa.Middleware;
namespace KoaLogger {}
export = KoaLogger;
}
