// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/cce31af92dc06fbd620d48ff55a9904be20ddc61/koa-json/index.d.ts
declare module 'koa-json' {
// Type definitions for koa-json v2.x
// Project: https://github.com/koajs/json
// Definitions by: Alex Friedman <https://github.com/brooklyndev/>
// Definitions: https://github.com/brooklyndev/DefinitelyTyped

/* =================== USAGE ===================

    import * as Koa from 'koa';
    import * as json from 'koa-json';

    const app = new Koa();
    app.use(json());

 =============================================== */

import * as Koa from 'koa';

function json(opts?: {

    /**
     * default to pretty response [true]
    */
    pretty?: boolean,

    /**
     * optional query-string param for pretty responses [none]
     */
    param?: string,

    /**
     * JSON spaces [2]
     */
    spaces?: number
}): Koa.Middleware;
namespace json { }
export = json;
}
