// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/1fe97bbf37387bb737d1581bc18d5bdc90022a6f/koa-send/index.d.ts
declare module 'koa-send' {
// Type definitions for koa-send v3.3
// Project: https://github.com/koajs/send
// Definitions by: Peter Safranek <https://github.com/pe8ter>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

import * as Koa from 'koa';

interface ISendOptions {
    root?: string;
    index?: string;
    maxAge?: number;
    hidden?: boolean;
    format?: boolean;
    gzip?: boolean;
    setHeaders?: Function;
    extensions?: string[];
}

function send(ctx: Koa.Context, path: string, opts?: ISendOptions): Promise<string>;

namespace send {}

export = send;
}
